apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: amazon-lab
spec:
  replicas: 8
  selector:
    matchLabels: {app: order-service}
  template:
    metadata:
      labels: {app: order-service}
    spec:
      containers:
        - name: app
          image: localhost:5000/order-service:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/amazonlab
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef: {name: postgres-secret, key: POSTGRES_PASSWORD}
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "35"
            - name: SERVER_TOMCAT_THREADS_MAX
              value: "400"
          ports: [{containerPort: 8080}]
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: amazon-lab
spec:
  type: NodePort
  selector: {app: order-service}
  ports: [{port: 8080, targetPort: 8080, nodePort: 30080}]
