apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopaholic
  namespace: amazon-lab
spec:
  replicas: 1
  selector:
    matchLabels: {app: shopaholic}
  template:
    metadata:
      labels: {app: shopaholic}
    spec:
      containers:
        - name: shopaholic
          image: localhost:5000/shopaholic:v1
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonSerializer"
          ports: [{containerPort: 8080}]
---
apiVersion: v1
kind: Service
metadata:
  name: shopaholic
  namespace: amazon-lab
spec:
  type: NodePort
  selector: {app: shopaholic}
  ports: [{port: 8080, targetPort: 8080, nodePort: 30081}]
