--liquibase formatted sql

--changeset denis:001-create-product-table
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price NUMERIC(38,2)
);
