--liquibase formatted sql

--changeset denis:002-create-warehouse-table
CREATE TABLE warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    location VARCHAR(255)
);
