--liquibase formatted sql

--changeset denis:003-create-customer-table
CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    city VARCHAR(255)
);
