--liquibase formatted sql

--changeset denis:004-create-inventory-table
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES product(id),
    warehouse_id BIGINT REFERENCES warehouse(id),
    quantity INTEGER
);

--changeset denis:004b-create-inventory-indexes
CREATE INDEX idx_inventory_product ON inventory(product_id);
CREATE INDEX idx_inventory_warehouse ON inventory(warehouse_id);
