--liquibase formatted sql

--changeset denis:005-create-orders-table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES product(id),
    customer_id BIGINT REFERENCES customer(id),
    warehouse_id BIGINT REFERENCES warehouse(id),
    price_at_order_time NUMERIC(38,2),
    idempotency_key VARCHAR(255)
);

--changeset denis:005b-create-idempotency-index
CREATE INDEX idx_orders_idempotency_key ON orders(idempotency_key);
