spring.datasource.url=jdbc:postgresql://postgres:5432/amaxonlab
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=8080